=== FriendlyNPC/starter-lab06/data/bonanza.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
Bob's Build a burger Order Placement data
-->


<!-- An order identifies customer, order type, burgers and special stuff  -->
<!ELEMENT order (customer, delivery?, burger+, special?, name?)>

<!-- A customer is identified by their name -->
<!ELEMENT customer (#PCDATA)>

<!-- An order can be eat-in, take out, or delivery, customer specified -->
<!ATTLIST order
    type (eatin|takeout|delivery) #REQUIRED
>

<!-- An order to be delivered will need delivery instructions-->
<!ELEMENT delivery (#PCDATA)>

<!-- special instructions -->
<!ELEMENT special (#PCDATA)>

<!-- the tasty burgers to be specified individually 
    burger options:
    1 of 5 patties
    up to 2 cheeses
    any number of toppings
    any number of sauces
    special instructions
    an optional name, should the customer with to propose as a menu item
-->
<!ELEMENT burger (patty, cheeses?, topping*, sauce*, instructions?, name?)>


<!-- the meaty goodness of the burger
    can select 1 of 5 patty types
-->
<!ELEMENT patty (#PCDATA)>
<!ATTLIST patty
    type (beef|pork|turkey|bison|vege) "beef"
>

<!-- the cheesy goodness of the buger, can be of two cheese types, one on top 
and on bottom -->
<!ELEMENT cheeses (EMPTY)>
<!ATTLIST cheeses
    top (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
    bottom (american|swiss|jack|blue|gruyere|gouda|aged|goat|brie) #IMPLIED
>

<!-- any number of toppings, will be handled individually-->
<!ELEMENT toppings (#PCDATA)>
<!ATTLIST toppings
    type (lettuce|tomato|raw|dill|roasted|shrooms|salca|bacon|chilies|fkchili|avacado|egg|porkbelly) #REQUIRED
>

<!-- sauce anre similar to toppings -->
<!ELEMENT sauce (EMPTY)>
<!ATTLIST sauce
    type (ketchup|mustard|mayo|fksauce) #REQUIRED
>

<!-- any instructions for the burger -->
<!ELEMENT instructions (#PCDATA)>

<!-- a name the customer can give the burger -->
<!ELEMENT name (#PCDATA)>

=== FriendlyNPC/starter-lab06/data/order2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE order SYSTEM 'bonanza.dtd'>

<order type="takeout">
    <customer>George</customer>
    <burger>
        <patty type="beef" />
        <cheeses top="american" bottom="swiss" />
        <toppings type="shrooms" />
        <sauce type="ketchup"/>
        <sauce type="mayo" />
    </burger>
    <burger>
        <patty type="beef" />
        <cheeses top="gruyerer" />
        <toppings type="shrooms" />
        <sauce type="ketchup"/>
        <sauce type="mayo" />
    </burger>
    <burger>
        <patty type="beef" />
        <cheeses top="gruyerer" />
        <toppings type="shrooms" />
        <sauce type="ketchup"/>
        <sauce type="mayo" />
    </burger>
</order>
